var numbers = [1, 2, 3, 4, 5];
var fruits = ["apple", "banana", "orange"];
var mixedArray = [1, "two", true, { name: "John" }];

console.log (mixedArray);
console.log (fruits);
console.log (numbers);


for (let i = 0; i < 5; i++) {
    console.log(i);
}


let i = 0;
while (i < 5) {
    console.log(i);
    i++;
}

 var name = "prem choudhary";
  console.log(name);

  const nam ="prem choudhary";
  console.log(name);

  var j = 10;
  const k = 10;
  let l = 10; 

  console.log(j )
  console.log(k )
  console.log(l )

//  so in this way codeing is heard 
// why is use for loop in js ??? 
//  what is use for araay in js 




